export const RECEIVED_RESTAURANTS = 'RECEIVED_RESTAURANTS';
export const REFINED_RESTAURANTS = 'REFINED_RESTAURANTS';
export const RESTAURANT_DETAILS = 'RESTAURANT_DETAILS'
export const MODAL_SHOW = 'MODAL_SHOW';
export const CURRENT_PAGE = 'CURRENT_PAGE';
export const TOTAL_ENTRIES = 'TOTAL_ENTRIES';